- defaults:
    link:
      create: true
      relink: true
      force: false
      backup: true

- link:
    ~/.bash_aliases: home_files/.bash_aliases
    ~/.bash_profile: home_files/.bash_profile
    ~/.bashrc: home_files/.bashrc

- shell:
   - [source ~/.bash_profile, Source bash profile]

