- apt:
    - curl

- link:
    ~/.copilot/instructions/direct_fable.instructions.md: home_files/.copilot/instructions/direct_fable.instructions.md
    ~/bin/copilot: home_files/bin/copilot
    ~/.aliases/copilot.sh: home_files/.aliases/copilot.sh

- shell:
  -
    command: helpers/copilot_setup.sh
    stdout: true
    stdin: true
    stderr: true
