- defaults:
    link:
      create: true
      relink: true
      force: false
      backup: true

- shell:
  -
    command: helpers/ohmyzsh_setup.sh
    stdout: true
    stdin: true
    stderr: true

- link:
    ~/.zsh_aliases: home_files/.zsh_aliases
    ~/.zsh_prompt: home_files/.zsh_prompt
    ~/.zshenv: home_files/.zshenv
    ~/.zshrc:
      path: home_files/.ohmyzshrc
